spring.application.name=backend

# MQTT - Broker prive local
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=Spring-Boot-Backend-Marwane
mqtt.topic=emsi/pfa/marwane_mouad/weather/+/data
mqtt.username=backend
mqtt.password=backend123

# PostgreSQL - donnees statiques
spring.datasource.url=jdbc:postgresql://localhost:5432/meteo_db
spring.datasource.username=meteo_user
spring.datasource.password=meteo_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# InfluxDB - donnees temps reel
influxdb.url=http://localhost:8086
influxdb.token=token-secret-influxdb
influxdb.org=emsi-iot
influxdb.bucket=weather_data

# JWT
jwt.secret=iHy1WQ9HRASqQ5qigtcrFNvs86PrhpcuoxlHNa/iKKA=
jwt.expiration=86400000

# Seuils alertes meteo
alertes.seuil.vent-critique=80.0
alertes.seuil.temp-max=45.0
alertes.seuil.temp-min=0.0
alertes.seuil.batterie-faible=15

# FastAPI - microservice prediction ML
ia.api.url=http://localhost:8000
