spring.application.name=backend
# Configuration MQTT (HiveMQ Public pour le moment)
mqtt.broker.url=tcp://broker.hivemq.com:1883
mqtt.client.id=Spring-Boot-Backend-Marwane
# Le "+" permet d'écouter toutes les stations (ST-CASABLANCA, ST-RABAT, etc.)
mqtt.topic=emsi/pfa/marwane_mouad/weather/+/data

# ==========================================
# CONFIGURATION POSTGRESQL (Méta-données)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_meteo_db
spring.datasource.username=root
spring.datasource.password=rootpassword
# Hibernate va créer les tables SQL automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURATION INFLUXDB (Capteurs)
# ==========================================
influxdb.url=http://localhost:8086
influxdb.token=mon-token-ultra-secret-12345
influxdb.org=emsi-iot
influxdb.bucket=meteo-data

# Demander à Spring Boot de créer les tables automatiquement d'après tes classes Java


# Activer l'interface web pour voir nos données !
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Seuils d'alertes Météo
alertes.seuil.vent-critique=80.0
alertes.seuil.temp-max=45.0
alertes.seuil.temp-min=0.0
alertes.seuil.batterie-faible=15
#FastAPI --> Micro-service pred
ia.api.url=http://localhost:8000