spring.application.name=backend

# ??????????????????????????????????????
# MQTT ? Broker privé local
# ??????????????????????????????????????
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=Spring-Boot-Backend-Marwane
mqtt.topic=emsi/pfa/marwane_mouad/weather/+/data
mqtt.username=backend
mqtt.password=backend123

# ??????????????????????????????????????
# POSTGRESQL ? données statiques
# ??????????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/meteo_db
spring.datasource.username=meteo_user
spring.datasource.password=meteo_pass
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ??????????????????????????????????????
# INFLUXDB ? données temps réel
# ??????????????????????????????????????
influxdb.url=http://localhost:8086
influxdb.token=token-secret-influxdb
influxdb.org=emsi-iot
influxdb.bucket=weather_data