[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"

[[chip]]
name = "pressure-sensor"
binary = "chips/pressure-sensor.chip.wasm"

[[chip]]
name = "wind-sensor"
binary = "chips/wind-sensor.chip.wasm"